### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by Ikhwansong** [JoanMartin/trackanimation#15]
Error 1. 
  File "/home/ihsong/anaconda3/envs/IRST_CNN/lib/python3.6/site-packages/trackanimation/utils.py", line 144, in get_coordinates
    d = geo_dist.VincentyDistance(kilometers=distance_km)

AttributeError: module 'geopy.distance' has no attribute 'VincentyDistance'

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Error 2.
sant_josep_trk = sant_josep_trk.set_colors('Speed', individual_tracks=True)

AttributeError: 'NoneType' object has no attribute 'set_colors'

**Comment by limkokhole** [comment]
Just want to note that `VincentyDistance` [deprecated](https://stackoverflow.com/a/61460267/1074998), need changed it to `distance`.
