### ISSUE TITLE
总结一下我使用该项目遇到的问题及解决办法

### ISSUE THREAD

**Issue by xiaosuqi1778** [JoanMartin/trackanimation#20]
- FileNotFoundError: [WinError 2]
没有下载[ffmpeg](https://blog.csdn.net/qq_33697094/article/details/112718101)
- urllib.error.HTTPError: HTTP Error 403: Forbidden
[urllib.error.HTTPError: HTTP Error 403: Forbidden](https://github.com/JoanMartin/trackanimation/issues/16)
- http请求报错：502 Bad Gateway
由于我所在地区难以访问openstreetmap，需要使用代理，同一代理访问多次也会被禁止，需要更换结点
- 'XAxis' object has no attribute '_gridOnMajor'
https://github.com/plotly/plotly.py/issues/2913

**Comment by bakikocabasa** [comment]
you need to install ffmpeg, please refer to chatgpt for such installation
