### ISSUE TITLE
Change aspect as option? (auto,equal...)

### ISSUE THREAD

**Issue by k2OS** [JoanMartin/trackanimation#4]
Very nice module.. I want use this to generate really nice videoes showing my travels.. However, the aspect ratio in the call to imshow is set to 'auto', making for really weird maps, unless I've happened to 
travel within a 1:1 square area - can I pass 'equal' on to imshow() somehow or do I have to recompile for each mode I want?

I'm browsing the documentation PDF, but I don't speak spanish, so it's not to too much use for me :)

Cheers!

/rené

**Comment by k2OS** [comment]
To answer my own question: In animation.py change init:
`    def __init__(self, df_points, dpi=100, bg_map=True,  map_transparency=0.5):`
To:
`    def __init__(self, df_points, dpi=100, bg_map=True, aspect='equal', map_transparency=0.5):`

and change the following: 
`            if bg_map:
                self.map.append(smopy.Map((min_lat, min_lng, max_lat, max_lng)))
                self.axarr[i].imshow(self.map[i].img, aspect='auto', alpha=map_transparency)
`
to 
`            if bg_map:
                self.map.append(smopy.Map((min_lat, min_lng, max_lat, max_lng)))
                self.axarr[i].imshow(self.map[i].img, aspect=aspect, alpha=map_transparency)
`
and now I can get nice maps that don't look squashed in any direction :)

Cheers!

/rené

**Comment by JoanMartin** [comment]
Hi @k2OS ,

thank you so much for your contribution! I have made a new release 1.0.5 with this fix.

Sorry for the documentation. I have in mind to make a good documentation in english, but right now I don't have too much time :/

I hope you enjoy making videos of your travels! :)
